PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE User(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
CREATE TABLE Playlist(id INTEGER PRIMARY KEY AUTOINCREMENT, userId INTEGER REFERENCES User(id) ON DELETE CASCADE, name TEXT NOT NULL);
CREATE TABLE Collection(id INTEGER PRIMARY KEY AUTOINCREMENT, parentId INTEGER REFERENCES Collection(id) ON DELETE CASCADE, name TEXT NOT NULL);
CREATE TABLE Media(id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT NOT NULL, name TEXT NOT NULL);


CREATE TABLE PlaylistMedia(playlistId INTEGER REFERENCES Playlist(id) ON DELETE CASCADE, mediaId INTEGER REFERENCES Media(id) ON DELETE CASCADE, bookmark INTEGER);
CREATE TABLE CollectionMedia(collectionId INTEGER REFERENCES Collection(id) ON DELETE CASCADE, mediaId INTEGER REFERENCES Media(id) ON DELETE CASCADE);
COMMIT;
